import "./globals.css";
import { Inter } from "next/font/google";
import Headers from "./component/Headers/header.jsx";
import Fotter from "./component/Fotter/Index";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <div>
          <Headers />
        </div>
        {children}
        <div>
          <Fotter />
        </div>
      </body>
    </html>
  );
}
